version: '3.8'

services:
  front-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: bfm-front-app-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

